# settings.py
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 960

WINDOW_CENTER_X = int(WINDOW_WIDTH / 2)
WINDOW_CENTER_Y = int(WINDOW_HEIGHT / 2)

WINDOW_SCALE = 1.0
WINDOW_SCALE_X = 1.0
WINDOW_SCALE_Y = 1.0

WINDOW_TITLE = "CONTACT"
PLAYER_SCALING = 1.0
